[tool.poetry]
name = "quacc"
version = "0.1.0"
description = ""
authors = ["Lorenzo Volpi <lorenzo.volpi@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
quapy = "^0.1.7"
pandas = "^2.0.3"
jinja2 = "^3.1.2"
pyyaml = "^6.0.1"
logging = "^0.4.9.6"

[tool.poetry.scripts]
main = "quacc.main:main"
comp = "quacc.main:estimate_comparison"
tohost = "scp_sync:scp_sync_to_host"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pylance = "^0.5.9"
pytest-mock = "^3.11.1"
pytest-cov = "^4.1.0"
win11toast = "^0.32"
tabulate = "^0.9.0"
paramiko = "^3.3.1"

[tool.pytest.ini_options]
addopts = "--cov=quacc --capture=tee-sys"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true

