[tool.poetry]
name = "quacc"
version = "0.1.0"
description = ""
authors = ["Lorenzo Volpi <lorenzo.volpi@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
quapy = "^0.1.7"
pandas = "^2.0.3"
jinja2 = "^3.1.2"
pyyaml = "^6.0.1"
logging = "^0.4.9.6"
abstention = "^0.1.3.1"

[tool.poetry.scripts]
main = "quacc.main:main"
run = "run:run"
panel = "qcpanel.run:run"
sync_up = "remote:sync_code"
sync_down = "remote:sync_output"
merge_data = "merge_data:run"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pylance = "^0.5.9"
pytest-mock = "^3.11.1"
pytest-cov = "^4.1.0"
tabulate = "^0.9.0"
paramiko = "^3.3.1"
panel = "^1.3.1"
ipympl = "^0.9.3"
ipykernel = "^6.26.0"
ipywidgets-bokeh = "^1.5.0"
pandas-stubs = "^2.1.1.230928"

[tool.pytest.ini_options]
addopts = "--cov=quacc --capture=tee-sys"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
prefer-active-python = true

