[tool.poetry]
name = "quacc"
version = "0.1.0"
description = ""
authors = ["Lorenzo Volpi <lorenzo.volpi@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
quapy = "^0.1.7"
pandas = "^2.0.3"
jinja2 = "^3.1.2"
pyyaml = "^6.0.1"
logging = "^0.4.9.6"
abstention = "^0.1.3.1"
pytest = "^8.0.0"
seaborn = "^0.13.2"

[tool.poetry.scripts]
main = "quacc.main:main"
run = "run:run"
pnl = "qcpanel.run:run"
dash = "qcdash.app:run"
sync_up = "remote:sync_code"
sync_down = "remote:sync_output"
merge_data = "merge_data:run"

[tool.poe]
poetry_command = ""

[tool.poe.tasks]
ilona = "ssh volpi@ilona.isti.cnr.it"
dash = "gunicorn qcdash.app:server -b ilona.isti.cnr.it:33421"

[tool.poe.tasks.logr]
shell = """
    scp {$HOST}:~/tesi/quacc.log ~/tesi/remote.log &> /dev/null
    ssh {$HOST} tail -n 0 -f /home/volpi/tesi/quacc.log >> ~/tesi/remote.log
"""
[tool.poe.tasks.logrf]
shell = """
    ssh {$HOST} tail -n 500 -f /home/volpi/tesi/quacc.log | bat -P --language=log
"""
[tool.poe.tasks.logf]
shell = """
    tail -n 500 -f /home/lorev/tesi/quacc.log | bat --paging=never --language log
"""

interpreter = "fish"
env = { HOST = "volpi@ilona.isti.cnr.it" }

[tool.poetry.group.dev.dependencies]
pylance = "^0.5.9"
pytest-mock = "^3.11.1"
pytest-cov = "^4.1.0"
tabulate = "^0.9.0"
paramiko = "^3.3.1"
panel = "^1.3.1"
ipympl = "^0.9.3"
ipykernel = "^6.26.0"
ipywidgets-bokeh = "^1.5.0"
pandas-stubs = "^2.1.1.230928"
dash = "^2.14.1"
dash-bootstrap-components = "^1.5.0"
gunicorn = "^21.2.0"

[tool.pytest.ini_options]
addopts = "--cov=quacc -rA --cov-report html"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120